Mp/test area
designunit/pat-service pull request #3
Opened 2020-01-26 21:49 UTC by modernpacifist

2020-01-27 11:51 UTC, tmshv requested changes
has unnecessary bin

2020-01-30 04:56 UTC, modernpacifist commented
> has unnecessary bin

you mean __pycache__?

2020-01-30 13:10 UTC, tmshv requested changes
It has already committed binaries

2020-01-30 14:36 UTC, modernpacifist commented
Can you specify the files?

2020-01-30 16:28 UTC, tmshv reviewed
now looks fine
but do nothing

2020-01-30 16:53 UTC, modernpacifist commented
Okay, no problem.

2020-02-20 16:43 UTC, tmshv commented on math_lib.py
> +    return direction * math.tan(get_radians(radians))
`math.radians`

2020-02-20 16:55 UTC, tmshv commented on paint_lib.py
> +
```py
angle = math.radians(45)
length = img_width
x = math.cos(angle) * length
y = math.sin(angle) * length
```

2020-02-20 18:00 UTC, tmshv commented on pattern.py
> +        self.gap_length = gap
`self.dash = [...]`

2021-05-22 09:55 UTC, closed without merging